version: "3"

services: 
  load_balancer: 
      image: nginxapp
      ports:
        - 8080:8080
  nodeapp1: 
      image: nodeapp
      environment: 
        - APPID=2222
  nodeapp2:
      image: nodeapp
      environment:
        - APPID=3333
  nodeapp3:
    image: nodeapp
    environment:
      - APPID=4444